import numpy as np
import math

class MLP:

    """
    Constructor: Computes MLP.

    Args:
        Layer (array): tamaños de las capas
        seed (scalar): seed of the random numeric.
        epislom (scalar) : random initialization range. e.j: 1 = [-1..1], 2 = [-2,2]...
    """

    def __init__(self,Layers, seed=0, epislom = 0.12):
        np.random.seed(seed)
        ## TO-DO
        self.layers = Layers
        numL = len(Layers)
        self.thetas =[]
        for i in range(numL-1):
            ts = np.random.uniform(-epislom,epislom, [Layers[i+1],Layers[i]+1])
            self.thetas.append(ts)
            #print("theta",i,": ",ts," Tamaño: ",ts.shape)
            
        #print("thetas: ", self.thetas)

        """
    Reset the theta matrix created in the constructor by both theta matrix manualy loaded.

    Args:
        theta1 (array_like): Weights for the first layer in the neural network.
        theta2 (array_like): Weights for the second layer in the neural network.
    """
    def new_trained(self,theta1,theta2):
        self.theta1 = theta1
        self.theta2 = theta2
        
    """
    Num elements in the training data. (private)

    Args:
        x (array_like): input data. 
    """
    def _size(self,x):
        return x.shape[0]
    
    """
    Computes de sigmoid function of z (private)

    Args:
        z (array_like): activation signal received by the layer.
    """
    def _sigmoid(self,z):
        el = np.exp(-z)
        dev = (1/(1+el))
        return dev

    """
    Computes de sigmoid derivation of de activation (private)

    Args:
        a (array_like): activation received by the layer.
    """   
    def _sigmoidPrime(self,a):
        gp = a*(1-a)
        return gp

    """
    Run the feedwordwar neural network step

    Args:
        x (array_like): input of the neural network.

	Return 
	------
	a1,a2,a3 (array_like): activation functions of each layers
    z2,z3 (array_like): signal fuction of two last layers
    """
    def feedforward(self,x):
        a = []
        z = []
        a1 = np.hstack([np.ones((self._size(x), 1)), x])
        a.append(a1)
        #print("a1: ", a1.shape, "esperado: ", x.shape[0],"x", x.shape[1]+1)
        rango = len(self.thetas)
        for i in range(rango-1):
            auxZ = a[i] @ self.thetas[i].T
            auxA = self._sigmoid(auxZ)
            auxA = np.hstack([np.ones((self._size(auxA), 1)), auxA])
            #print("a", i+2, ": ", auxA.shape, "esperado: ", a[i].shape[0],"x", self.thetas[i].shape[0]+1)
            z.append(auxZ)
            a.append(auxA)
        
        auxZ = a[rango-1] @ self.thetas[rango-1].T
        auxA = self._sigmoid(auxZ)
        #print("a", rango+1, ": ", auxA.shape, "esperado: ", a[rango-1].shape[0],"x", self.thetas[rango-1].shape[0])
        z.append(auxZ)
        a.append(auxA)
        return a,z # devolvemos a parte de las activaciones, los valores sin ejecutar la función de activación

    """
    Computes only the cost of a previously generated output (private)

    Args:
        yPrime (array_like): output generated by neural network.
        y (array_like): output from the dataset
        lambda_ (scalar): regularization parameter

	Return 
	------
	J (scalar): the cost.
    """
    def compute_cost(self, yPrime,y, lambda_):
        yp = np.array(yPrime)
        #print("yp: ", yp.shape)
        #print("y: ", y.shape)
        p1 = y * np.log(yPrime)
        p2 = (1 - y) * (np.log((1-yPrime)))

        su = p1+p2
        su = np.sum(su)

        m = self._size(y)

        dev = (-1/m) * su
        dev = dev + self._regularizationL2Cost(m,lambda_)
        return dev
    

    """
    Get the class with highest activation value

    Args:
        a3 (array_like): output generated by neural network.

	Return 
	------
	p (scalar): the class index with the highest activation value.
    """
    def predict(self,a3):
        p = np.argmax(a3.T, axis=0)
        return p
    

    """
    Compute the gradients of both theta matrix parámeters and cost J

    Args:
        x (array_like): input of the neural network.
        y (array_like): output of the neural network.
        lambda_ (scalar): regularization.

	Return 
	------
	J: cost
    grad1, grad2: the gradient matrix (same shape than theta1 and theta2)
    """
    def compute_gradients(self, x, y, lambda_):
        a,z = self.feedforward(x)

        long = len(a)
        J=self.compute_cost(a[long-1],y,lambda_)
        
        dlts = []
        dltL=a[long-1]-y
        #print("dltL tamaño: ", dltL.shape)
        dlts.append(dltL)

        #print("dltL tamaño: ", dltL.shape)
        #print("self.thetas[long-2]: ", self.thetas[long-2].shape)
        dltL_1 = np.dot(dltL,self.thetas[long-2])*self._sigmoidPrime(a[long-2])
        #print("dltL_1 tamaño: ", dltL_1.shape)
        dlts.append(dltL_1)

        for i in range(long-3, 0, -1):
            lng = len(dlts)
            #print("dlts[lng-1][:, 1:] tamaño: ", dlts[lng-1][:, 1:].shape)
            #print("self.thetas[i] tamaño: ", self.thetas[i].shape)
            auxDlt =np.dot(dlts[lng-1][:, 1:],self.thetas[i])*self._sigmoidPrime(a[i])
            #print("auxDlt tamaño: ", auxDlt.shape)
            dlts.append(auxDlt)
        
        #print("cantidad de deltas: ", len(dlts))

        #dar la vuelta a la lista de deltas
        invDlts =dlts[::-1]

        grad = []
        for i in range(long-1):
            auxGrad = np.zeros(self.thetas[i].shape)
            #print("grad", i+1, "tamaño: ", auxGrad.shape)
            grad.append(auxGrad)

        m = self._size(x)

        g=[]
        for i in range(long-2):
            auxG = np.dot(invDlts[i][:, 1:].T,a[i])/m
            #print("g", i+1, "tamaño: ", auxG.shape)
            g.append(auxG)

        gL = np.dot(dltL.T,a[long-2])
        #print("gL tamaño: ", gL.shape)
        g.append(gL)

        for i in range(long-1):
            g[i][:,1:] = g[i][:,1:]+self._regularizationL2Gradient(self.thetas[i],lambda_,m)
            grad[i]+=g[i]

        return (J, grad)
    
    """
    Compute L2 regularization gradient

    Args:
        theta (array_like): a theta matrix to calculate the regularization.
        lambda_ (scalar): regularization.
        m (scalar): the size of the X examples.

	Return 
	------
	L2 Gradient value
    """
    def _regularizationL2Gradient(self, theta, lambda_, m):
        #print(theta[:,1:])
        L2 = theta[:,1:] * (lambda_/m)
        return L2
    
    
    """
    Compute L2 regularization cost

    Args:
        lambda_ (scalar): regularization.
        m (scalar): the size of the X examples.

	Return 
	------
	L2 cost value
    """

    def _regularizationL2Cost(self, m, lambda_):
        L2=0
        rango = len(self.thetas)

        for i in range(rango):
            auxT = self.thetas[i][:, 1:]
            auxT = auxT**2
            auxT = auxT.sum()
            L2 = L2+auxT

        L2= ((L2*lambda_)/(2*m))
        return L2
    
    
    def backpropagation(self, x, y, alpha, lambda_, numIte, verbose=0):
        Jhistory = []
        for i in range(numIte):
            J = 0
            ##TO-DO: calculate gradients and update both theta matrix
            J,g=self.compute_gradients(x, y, lambda_)
            long = len(g)
            for i in range(long-1):
                self.thetas[i]-=alpha*g[i]
            Jhistory.append(J)
            if verbose > 0 :
                if i % verbose == 0 or i == (numIte-1):
                    print(f"Iteration {(i+1):6}: Cost {float(J):8.4f}   ")
        
        return Jhistory
    


"""
target_gradient funcitón of gradient test 1
"""
def target_gradient(input_layer_size,hidden_layer_size,num_labels,x,y,reg_param):
    mlp = MLP(input_layer_size,hidden_layer_size,num_labels)
    J, grad1, grad2 = mlp.compute_gradients(x,y,reg_param)
    return J, grad1, grad2, mlp.theta1, mlp.theta2


"""
costNN funcitón of gradient test 1
"""
def costNN(Theta1, Theta2,x, ys, reg_param):
    mlp = MLP(x.shape[1],1, ys.shape[1])
    mlp.new_trained(Theta1,Theta2)
    J, grad1, grad2 = mlp.compute_gradients(x,ys,reg_param)
    return J, grad1, grad2


"""
mlp_backprop_predict 2 to be execute test 2
"""
def MLP_backprop_predict(X_train,y_train, X_test, alpha, lambda_, num_ite, verbose):
    mlp = MLP([X_train.shape[1],59,47,35,23,11,5])
    Jhistory = mlp.backpropagation(X_train,y_train,alpha,lambda_,num_ite,verbose)
    a,z= mlp.feedforward(X_test)
    range =len(a)
    y_pred=mlp.predict(a[range-1])
    return y_pred