import numpy as np
import math

class MLP:

    """
    Constructor: Computes MLP.

    Args:
        inputLayer (int): size of input
        hiddenLayer (int): size of hidden layer.
        outputLayer (int): size of output layer
        seed (scalar): seed of the random numeric.
        epislom (scalar) : random initialization range. e.j: 1 = [-1..1], 2 = [-2,2]...
    """

    def __init__(self,inputLayer,hidenLayer, outputLayer, seed=0, epislom = 0.12):
        np.random.seed(seed)
        ## TO-DO
        self.inputLayer = inputLayer
        self.hidenLayer = hidenLayer
        self.outputLayer = outputLayer
        t1 = np.random.uniform(-epislom,epislom, [hidenLayer,inputLayer+1])
        t2 = np.random.uniform(-epislom,epislom,[outputLayer,hidenLayer+1])
        self.new_trained(t1,t2)
        """
    Reset the theta matrix created in the constructor by both theta matrix manualy loaded.

    Args:
        theta1 (array_like): Weights for the first layer in the neural network.
        theta2 (array_like): Weights for the second layer in the neural network.
    """
    def new_trained(self,theta1,theta2):
        self.theta1 = theta1
        self.theta2 = theta2
        
    """
    Num elements in the training data. (private)

    Args:
        x (array_like): input data. 
    """
    def _size(self,x):
        return x.shape[0]
    
    """
    Computes de sigmoid function of z (private)

    Args:
        z (array_like): activation signal received by the layer.
    """
    def _sigmoid(self,z):
        el = np.exp(-z)
        dev = (1/(1+el))
        return dev

    """
    Computes de sigmoid derivation of de activation (private)

    Args:
        a (array_like): activation received by the layer.
    """   
    def _sigmoidPrime(self,a):
        gp = a*(1-a)
        return gp

    """
    Run the feedwordwar neural network step

    Args:
        x (array_like): input of the neural network.

	Return 
	------
	a1,a2,a3 (array_like): activation functions of each layers
    z2,z3 (array_like): signal fuction of two last layers
    """
    def feedforward(self,x):
        a1 = np.hstack([np.ones((self._size(x), 1)), x])
        z2 = a1 @ self.theta1.T 
        a2 = self._sigmoid(z2)
        a2 = np.hstack([np.ones((self._size(a2), 1)), a2])
        z3 = a2 @ self.theta2.T
        a3 = self._sigmoid(z3)
        return a1,a2,a3,z2,z3 # devolvemos a parte de las activaciones, los valores sin ejecutar la función de activación

    """
    Computes only the cost of a previously generated output (private)

    Args:
        yPrime (array_like): output generated by neural network.
        y (array_like): output from the dataset
        lambda_ (scalar): regularization parameter

	Return 
	------
	J (scalar): the cost.
    """
    def compute_cost(self, yPrime,y, lambda_): # es una función interna por eso empieza por _
        p1 = y * np.log(yPrime)
        p2 = (1 - y) * (np.log((1-yPrime)))

        su = p1+p2
        su = np.sum(su)

        m = self._size(y)

        dev = (-1/m) * su
        dev = dev + self._regularizationL2Cost(m,lambda_)
        return dev
    

    """
    Get the class with highest activation value

    Args:
        a3 (array_like): output generated by neural network.

	Return 
	------
	p (scalar): the class index with the highest activation value.
    """
    def predict(self,a3):
        p = np.argmax(a3.T, axis=0)
        return p
    

    """
    Compute the gradients of both theta matrix parámeters and cost J

    Args:
        x (array_like): input of the neural network.
        y (array_like): output of the neural network.
        lambda_ (scalar): regularization.

	Return 
	------
	J: cost
    grad1, grad2: the gradient matrix (same shape than theta1 and theta2)
    """
    def compute_gradients(self, x, y, lambda_):
        a1,a2,a3,z2,z3 = self.feedforward(x)

        J=self.compute_cost(a3,y,lambda_)
        dlt3=a3-y
        
        dlt2=np.dot(dlt3,self.theta2)*self._sigmoidPrime(a2)
        
        grad1=np.zeros(self.theta1.shape)
        grad2=np.zeros(self.theta2.shape)

        m = self._size(x)

        g1=np.dot(dlt2[:, 1:].T,a1)/m
        g2=np.dot(dlt3.T,a2)/m

        g1[:,1:] = g1[:,1:]+self._regularizationL2Gradient(self.theta1,lambda_,m)
        grad1+= g1
        g2[:,1:] = g2[:,1:]+self._regularizationL2Gradient(self.theta2,lambda_,m)
        grad2+=g2

        return (J, grad1, grad2)
    
    """
    Compute L2 regularization gradient

    Args:
        theta (array_like): a theta matrix to calculate the regularization.
        lambda_ (scalar): regularization.
        m (scalar): the size of the X examples.

	Return 
	------
	L2 Gradient value
    """
    def _regularizationL2Gradient(self, theta, lambda_, m):
        #print(theta[:,1:])
        L2 = theta[:,1:] * (lambda_/m)
        return L2
    
    
    """
    Compute L2 regularization cost

    Args:
        lambda_ (scalar): regularization.
        m (scalar): the size of the X examples.

	Return 
	------
	L2 cost value
    """

    def _regularizationL2Cost(self, m, lambda_):
        t1 =self.theta1[:, 1:]
        t2= self.theta2[:, 1:]
        t1=t1**2
        t2=t2**2
        t1=t1.sum()
        t2=t2.sum()
        L2= t1+t2
        L2= ((L2*lambda_)/(2*m))
        return L2
    
    
    def backpropagation(self, x, y, alpha, lambda_, numIte, verbose=0):
        Jhistory = []
        for i in range(numIte):
            J = 0
            ##TO-DO: calculate gradients and update both theta matrix
            J,g1,g2=self.compute_gradients(x, y, lambda_)
            self.theta1-=alpha*g1
            self.theta2-=alpha*g2
            Jhistory.append(J)
            if verbose > 0 :
                if i % verbose == 0 or i == (numIte-1):
                    print(f"Iteration {(i+1):6}: Cost {float(J):8.4f}   ")
        
        return Jhistory
    


"""
target_gradient funcitón of gradient test 1
"""
def target_gradient(input_layer_size,hidden_layer_size,num_labels,x,y,reg_param):
    mlp = MLP(input_layer_size,hidden_layer_size,num_labels)
    J, grad1, grad2 = mlp.compute_gradients(x,y,reg_param)
    return J, grad1, grad2, mlp.theta1, mlp.theta2


"""
costNN funcitón of gradient test 1
"""
def costNN(Theta1, Theta2,x, ys, reg_param):
    mlp = MLP(x.shape[1],1, ys.shape[1])
    mlp.new_trained(Theta1,Theta2)
    J, grad1, grad2 = mlp.compute_gradients(x,ys,reg_param)
    return J, grad1, grad2


"""
mlp_backprop_predict 2 to be execute test 2
"""
def MLP_backprop_predict(X_train,y_train, X_test, alpha, lambda_, num_ite, verbose):
    mlp = MLP(X_train.shape[1],25,y_train.shape[1])
    Jhistory = mlp.backpropagation(X_train,y_train,alpha,lambda_,num_ite,verbose)
    a3= mlp.feedforward(X_test)[2]
    y_pred=mlp.predict(a3)
    return y_pred